name: "regolith"
description: "Bedrock Addons compiler pipeline."
inputs:
  profile:
    description: "profile to run"
    default: "default"
    required: false
  github_token:
    description: "GitHub Token for getting private filters"
    default: ""
    required: false

runs:
  using: "composite"
  steps:
    - name: setup-git-credentials
      uses: de-vri-es/setup-git-credentials@v2.0.8
      if: ${{ inputs.github_token != '' }}
      with:
        credentials: https://user:${{ inputs.github_token }}@github.com/
    - name: deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: vx.x.x
    - name: nim
      uses: iffy/install-nim@v4.2.0
      with:
        version: stable
    - name: go
      uses: actions/setup-go@v4
      with:
        go-version: 1.19
    - name: list versions
      shell: bash
      run: |
        python --version
        node -v
        nim -v
        java -version
        deno --version
        dotnet --list-sdks
        go version
    - name: regolith
      shell: bash
      run: |
        wget -O regolith.tar.gz https://github.com/respectZ/regolith/releases/download/$(cat ${{ github.action_path }}/version)/regolith.tar.gz
        tar -xzf regolith.tar.gz
        mv regolith /usr/local/bin
        rm regolith.tar.gz
        chmod +x /usr/local/bin/regolith
    - name: install
      shell: bash
      run: regolith install-all
    - name: compile
      shell: bash
      run: regolith run ${{inputs.profile}}
